deploy:
  dropbox_path: /Builds/klayout-pymod # The path to the folder on Dropbox where the files will go
  artifacts_path: dist # can be a single file, or a path
  debug: true # if you want to see more logs
